version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    environment:
      - node.name=es-01
      - node.master=true
      - node.data=true
      - cluster.name=monitoring-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.collection.enabled=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./es-data-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

#https://github.com/xeraa/elastic-docker/blob/master/full_stack/docker-compose.yml
  metricbeat:
      image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
      container_name: metricbeat
      hostname: metricbeat
      user: root #To read the docker socket
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      # command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
      # command: filebeat -e -strict.perms=false
      command:
        - filebeat -e -strict.perms=false
        - rm -r /usr/share/metricbeat/modules.d/kafka.yml.disabled
      volumes:
        - ./metricbeat-data01:/usr/share/metricbeat/data
        - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
        - ./metricbeat/kafka.yml:/usr/share/metricbeat/modules.d/kafka.yml
        #The commented sections below enable Metricbeat to monitor the Docker host rather than the Metricbeat container. These are used by the system module.
        - /proc:/hostfs/proc:ro
        - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
        #Allows us to report on docker from the hosts information.
        - /var/run/docker.sock:/var/run/docker.sock
        #We mount the host filesystem so we can report on disk usage with the system module.
        - /:/hostfs:ro
      command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
      networks:
        - elk
      depends_on:
        - elasticsearch
        - zookeeper
        - kafka

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        read_only: true
    ports:
      - "9600:9600"
      - "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TEST_TOPIC: monitoring
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kafka
      - zookeeper

  kibana:
    image: kibana:${ELK_VERSION}
    ports:
      - "5601:5601"
    environment:
      - server.name=kibana
      - server.host="0"
      - elasticsearch.hosts=elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    networks:
      - elk
    depends_on:
      - elasticsearch

  zookeeper:
    image: zookeeper:3.5.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    # labels:
    #   - co.elastic.metrics/module=zookeeper
    #   - co.elastic.metrics/hosts=zookeeper:2181
    #   - co.elastic.metrics/metricsets=mntr,server
    networks:
      - elk

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    # build:
    #   context: kafka/kafka-docker/
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1001
      KAFKA_RESERVED_BROKER_MAX_ID: 1002
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL_SSL://0.0.0.0:19092, #PLAINTEXT_HOST://0.0.0.0:9091
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SSL://kafka:19092, #PLAINTEXT_HOST://kafka:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SSL:SSL, #PLAINTEXT_HOST:PLAINTEXT

      KAFKA_CREATE_TOPICS: "monitoring:3:1"   # Topic명:Partition개수:Replica개수
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_SSL_KEYSTORE_LOCATION: '/certs/docker.kafka.server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'dockerpass'
      KAFKA_SSL_KEYSTORE_TYPE: JKS
      KAFKA_SSL_KEY_PASSWORD: 'dockerpass'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/certs/docker.kafka.server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'dockerpass'
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_CLIENT_AUTH: 'required' #'none'


      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      # KAFKA_REST_CLIENT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: null
      # KAFKA_LISTENERS: SSL://127.0.0.1:19092
      # KAFKA_ADVERTISED_LISTENERS: SSL://127.0.0.1:19092
      # KAFKA_ADVERTISED_HOST_NAME:  'kafka'
      # KAFKA_ADVERTISED_PORT: 19092
      # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'INTERNAL'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka/certs:/certs
    # labels:
    #   - co.elastic.logs/module=kafka
    #   - co.elastic.metrics/module=kafka
    #   - co.elastic.metrics/metricsets=partition,consumergroup
    #   - co.elastic.metrics/hosts='$${data.container.name}:9091'
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9091:9091"
    depends_on:
      - zookeeper
    networks:
      - elk

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:2.0.0.2
    # restart: on-failure
    depends_on:
    - kafka
    - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "random"
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    ports:
    - "9000:9000"
    networks:
    - elk

  grafana:
      image: grafana/grafana
      container_name: grafana
      restart: always
      ports:
        - 3000:3000
      networks:
        - elk
      volumes:
       # - grafana-volume:/vol01/Docker/monitoring
       - ./grafana/data:/var/lib/grafana


  telegraf:
    image: telegraf:1.12.6
    container_name: telegraf
    privileged: true
    restart: always
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_MOUNT_PREFIX=/rootfs
    hostname: localhost
    #network_mode: host
    networks:
      - elk
    volumes:
      - /:/rootfs:ro
      - /proc:/rootfs/proc:ro
      - /sys:/rootfs/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf/ca.pem:/etc/telegraf/ca.pem
      - ./telegraf/cert.pem:/etc/telegraf/cert.pem
      - ./telegraf/key.pem:/etc/telegraf/key.pem



networks:
  elk:
    driver: bridge
