metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    # - "cpu"
    # - "diskio"
    - "healthcheck"
    # - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
- module: kafka
  metricsets:
   - broker
   # - consumer
   - consumergroup
   - partition
   # - producer
  period: 20s
  hosts: ["kafka:9092"]

processors:
  - add_cloud_metadata: ~

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://elasticsearch:9200"]
  # index: "metricbeat-kafka-%{[agent.version]}-%{+yyyy-MM-dd}"
# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:
  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)
  # In case you specify and additional path, the scheme is required: http://localhost:5601/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "http://kibana:5601"
